### ISSUE TITLE
[Feat Help] Gas

### ISSUE THREAD

**Issue by edersong** [ad-ha/repsolluzygas-async#1]
Hello, 
I have Gas contract.
Let me know if you need anything.

**Comment by ad-ha** [comment]
Great. Thanks.

If you are able, try to install this integration and see the data that comes on the log. You have to enable debug for the integration.

I would need the structure of Contracts data, for the gas contracts, and the invoices and costs data.

If the integration does not get data, which may happen, then we would need to get this from the Developer tools on Chrome, for example, and checking on Area de Clientes web.

**Comment by ad-ha** [comment]
@edersong, to activate the debug logs, you can either do:

Add the following to `configutation.yaml`:

```
logger:
  default: warning
  logs:
    # Repsol Luz y Gas
    custom_components.repsolluzygas: debug
```

Or by activating the logging here:
![image](https://github.com/ad-ha/repsolluzygas-async/assets/59612788/cdc8bd87-9130-4c22-b0c9-5d7e1945329e)
