### ISSUE TITLE
Only the electricity contract appears, but not the gas contract.

### ISSUE THREAD

**Issue by weto91** [ad-ha/repsolluzygas-async#21]
When I enter the Repsol credentials in the integration, only the electricity contract appears (which works perfectly), but in my case I also have a gas contract with Repsol, and it is not listed..

**Comment by ad-ha** [comment]
Hi, @weto91

Are you able to send me the DEBUG logs from your HA instance? (be careful with personal data that might appear on the logs).

I got that data before the latest changes to the API and it was all working well, so it might be just some minor changes from Repsol that broke it. As I only have an Electricity contract I cannot check it myself.

Once I get that, I will look into it and change whatever needs to be addressed.

Thanks

**Comment by ad-ha** [comment]
BTW @weto91

You may activate the debug logs incorporating this into `configuration.yaml`

```
logger:
  default: warning
  logs:
    # Repsol Luz y Gas
    custom_components.repsolluzygas: debug
```
